title = "QuickBounds"  # From Git
gitRepoUrl = "https://github.com/unityjaeger/QuickBounds" # From Git

gitSourceBranch = "main"
changelog = false

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Fast Spatial Queries"
description = "Uses a Bounding Volume Hierarchy (BVH) for efficient spatial intersection tests"

[[home.features]]
title = "Group System"
description = "Organize zones and trackable objects into logical groups"

[[home.features]]
title = "Shapes"
description = "Supports Cubes, Spheres and Cylinders"

# From git:
organizationName = "unityjaeger"
projectName = "QuickBounds"
url = "https://github.com/unityjaeger"
baseUrl = "/QuickBounds/"